<?php

namespace Appartoo\CarnetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ziftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ziftRepository extends EntityRepository
{
}
